server:
  port: 8765
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: calculationService
          uri: lb://CALCULATION-SERVICE
          predicates:
            - Path=/currency-calculate/**
        - id: exchangeModule
          uri: lb://CURRENCY-EXCHANGE-SERVICE
          predicates:
            - Path=/exchange-value/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
